In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
## Define the vocabulary size
voc_size=10000

In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4712, 632, 7755, 3023],
 [4712, 632, 7755, 6285],
 [4712, 7227, 7755, 4662],
 [9039, 7099, 8579, 8342, 5266],
 [9039, 7099, 8579, 8342, 619],
 [1011, 4712, 6565, 7755, 1192],
 [7900, 4118, 2745, 8342]]

In [12]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4712  632 7755 3023]
 [   0    0    0    0 4712  632 7755 6285]
 [   0    0    0    0 4712 7227 7755 4662]
 [   0    0    0 9039 7099 8579 8342 5266]
 [   0    0    0 9039 7099 8579 8342  619]
 [   0    0    0 1011 4712 6565 7755 1192]
 [   0    0    0    0 7900 4118 2745 8342]]


In [15]:
## feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 250ms/step


array([[[-0.04412924,  0.0497407 ,  0.04020013,  0.04921171,
          0.0404929 ,  0.02392009, -0.03191949,  0.04936571,
          0.02925125,  0.0311302 ],
        [-0.04412924,  0.0497407 ,  0.04020013,  0.04921171,
          0.0404929 ,  0.02392009, -0.03191949,  0.04936571,
          0.02925125,  0.0311302 ],
        [-0.04412924,  0.0497407 ,  0.04020013,  0.04921171,
          0.0404929 ,  0.02392009, -0.03191949,  0.04936571,
          0.02925125,  0.0311302 ],
        [-0.04412924,  0.0497407 ,  0.04020013,  0.04921171,
          0.0404929 ,  0.02392009, -0.03191949,  0.04936571,
          0.02925125,  0.0311302 ],
        [ 0.02014599, -0.02491572,  0.03089217,  0.01490292,
          0.02482666,  0.01092171,  0.0055876 ,  0.02069298,
         -0.00162138, -0.02465969],
        [-0.02777915,  0.0132115 , -0.0308175 ,  0.00913825,
         -0.0043311 ,  0.00411214, -0.04886907, -0.00241463,
          0.02297213,  0.03803011],
        [ 0.02810043, -0.00567336, -0.04693013,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 4712,  632, 7755, 3023])

In [20]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 125ms/step


array([[-0.04412924,  0.0497407 ,  0.04020013,  0.04921171,  0.0404929 ,
         0.02392009, -0.03191949,  0.04936571,  0.02925125,  0.0311302 ],
       [-0.04412924,  0.0497407 ,  0.04020013,  0.04921171,  0.0404929 ,
         0.02392009, -0.03191949,  0.04936571,  0.02925125,  0.0311302 ],
       [-0.04412924,  0.0497407 ,  0.04020013,  0.04921171,  0.0404929 ,
         0.02392009, -0.03191949,  0.04936571,  0.02925125,  0.0311302 ],
       [-0.04412924,  0.0497407 ,  0.04020013,  0.04921171,  0.0404929 ,
         0.02392009, -0.03191949,  0.04936571,  0.02925125,  0.0311302 ],
       [ 0.02014599, -0.02491572,  0.03089217,  0.01490292,  0.02482666,
         0.01092171,  0.0055876 ,  0.02069298, -0.00162138, -0.02465969],
       [-0.02777915,  0.0132115 , -0.0308175 ,  0.00913825, -0.0043311 ,
         0.00411214, -0.04886907, -0.00241463,  0.02297213,  0.03803011],
       [ 0.02810043, -0.00567336, -0.04693013,  0.03087169,  0.0381713 ,
        -0.03612611, -0.03679168,  0.04759734